language: go

go:
  - 1.12.x

go_import_path: github.com/appsody/appsody

os:
  - linux

services:
  - docker
install:
  - make get-cli

script:
<<<<<<< HEAD
  - make test
 
=======
  - . ./ci/build.sh .

# note before_deploy will run before each deploy provider
before_deploy:
  - . ./ci/release.sh .
>>>>>>> upstream/master

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file: ci/release/*
  file_glob: true
  on:
    tags: true
    repo: appsody/stacks
    branch: master